# put your configuration values here

[runtime]
log_level="DEBUG"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = false

[local_mongo]
database = "sample_analytics" 
collection_names = ["customers", "accounts", "transactions"]

[mongo_oplog]
database = "local" 
collection_names = ["oplog.rs"]